### PR TITLE
Bob patch

### PR DESCRIPTION
**Pull request by yurrriq**
@oubiwann, I'm submitting this as a PR so as not to step on your toes.

Per [my comment](https://github.com/lfex/xlfe/commit/9914a4bc268049a14a1b0f88a7b7c034bb27a59c#commitcomment-12124775) on the initial bob port commit I've run:

``` sh
mv bob/bob.lfe bob/example.lfe
```

I also removed the UTF-8 tests you added, since the other language tracks don't include them. It seems like the M.O. is to maintain as much parity between tracks as possible.

And now, using the workflow [you outlined](https://github.com/lfex/xlfe/commit/9914a4bc268049a14a1b0f88a7b7c034bb27a59c#commitcomment-12124691):

``` fish
# I use fish so some of my commands are a little different...
set -x ERL_LIBS (find deps -maxdepth 1 -mindepth 1 | tr '\n' ':')

# mv bob/example.lfe bob/bob.lfe

lfec -o bob bob/*.lfe
lfe -pa bob -noshell -eval "(eunit:test 'bob-tests '(verbose))" -s init stop

# mv bob/bob.lfe bob/example.lfe
```

``` erlang
======================== EUnit ========================
module 'bob-tests'
  bob-tests: responds-to-something_test...[0.003 s] ok
  bob-tests: responds-to-shouts_test...ok
  bob-tests: responds-to-questions_test...ok
  bob-tests: responds-to-forceful-talking_test...ok
  bob-tests: responds-to-acronyms_test...ok
  bob-tests: responds-to-forceful-questions_test...ok
  bob-tests: responds-to-shouting-with-special-characters_test...ok
  bob-tests: responds-to-shouting-numbers_test...ok
  bob-tests: responds-to-shouting-with-no-exclamation-mark_test...ok
  bob-tests: responds-to-statement-containing-question-mark_test...ok
  bob-tests: responds-to-silence_test...ok
  bob-tests: responds-to-prolonged-silence_test...ok
  bob-tests: responds-to-non-letters-with-question_test...ok
  bob-tests: responds-to-multiple-line-questions_test...ok
  bob-tests: responds-to-only-numbers_test...ok
  bob-tests: responds-to-question-with-only-numbers_test...ok
  bob-tests: responds-to-unicode-shout_test...ok
  bob-tests: responds-to-unicode-non-shout_test...ok
  [done in 0.057 s]
=======================================================
  All 18 tests passed.
```

### CODE REVIEW

**Comment by oubiwann** [comment]
Cool!

**Comment by oubiwann** [comment]
I've updated the workflow doc: 83ccbc46cb63db5048343d11a3e936b9f7ab6fa5

**Comment by yurrriq** [comment]
Great, thanks!

**Comment by yurrriq** [comment]
I made [a few tweaks](https://github.com/lfex/xlfe/compare/5122c975e69ad2336f72a9c2480ebf5a0c982dbe...6e88b865f88483aa6cfd3e1578aa47b9d611597c).

**Pull request merged**
